apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wakesafe-ai
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - image: REGION-docker.pkg.dev/PROJECT_ID/wakesafe/wakesafe-ai:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: PYTHONPATH
          value: "/app"
        - name: WAKESAFE_API_URL
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: wakesafe-api-url
        - name: WAKESAFE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: wakesafe-api-token
        - name: AI_SERVER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: ai-server-secret-key
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: mongodb-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: redis-url
        - name: GCS_BUCKET
          valueFrom:
            secretKeyRef:
              name: wakesafe-secrets
              key: gcs-bucket
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
